# Generated by Django 3.1.5 on 2021-05-21 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0015_auto_20210521_0905'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourSpecifique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dete', models.DateField(verbose_name='Jour')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('id_jour', models.IntegerField(verbose_name='Id du jour')),
                ('responsable', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rdv.responsable')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rdv.service')),
            ],
        ),
    ]
