# Generated by Django 3.1.5 on 2021-05-21 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0015_auto_20210521_0905'),
        ('administration', '0002_jourspecifique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jourspecifique',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rdv.responsable'),
        ),
    ]
