# Generated by Django 3.1.5 on 2021-05-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20210521_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jourspecifique',
            old_name='dete',
            new_name='date',
        ),
    ]
