# Generated by Django 3.1.5 on 2021-05-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20210525_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='jourspecifique',
            name='couleur',
            field=models.CharField(max_length=50, null=True, verbose_name='Couleur du JS'),
        ),
    ]
