# Generated by Django 3.1.5 on 2021-02-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_n', models.DateField(auto_now_add=True, verbose_name='Date notification')),
                ('heure_n', models.TimeField(auto_now_add=True, verbose_name='Heure événement')),
                ('objet_n', models.CharField(default=' ', max_length=500, verbose_name='Objet de la notification')),
                ('object_concern', models.IntegerField(verbose_name="Id de l'objet concerné")),
                ('vue', models.BooleanField(default=False, verbose_name='Vue')),
            ],
        ),
    ]
