# Generated by Django 3.1.5 on 2021-02-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilites', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='id_user_type',
            field=models.IntegerField(null=True, verbose_name="Id de l'utilisateur concerné"),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_type',
            field=models.CharField(max_length=200, null=True, verbose_name="Type d'utilisateur concerné"),
        ),
    ]
