# Generated by Django 3.1.5 on 2021-02-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilites', '0003_auto_20210215_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type_n',
            field=models.CharField(default='evenement', max_length=20, null=True, verbose_name='Type de notification'),
        ),
    ]
