# Generated by Django 3.1.5 on 2021-02-17 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disponibilites', '0004_notification_type_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='id_user_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='evt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='disponibilites.evenement'),
        ),
        migrations.AddField(
            model_name='notification',
            name='rdv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rdv.rendezvous'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_n',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
