# Generated by Django 3.1.5 on 2021-02-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilites', '0005_auto_20210217_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='object_concern',
        ),
    ]
