# Generated by Django 3.1.5 on 2021-02-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilites', '0006_remove_notification_object_concern'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_name',
            field=models.CharField(default=' ', max_length=300, null=True, verbose_name="Nom de l'utilisateur"),
        ),
    ]
