# Generated by Django 3.1.5 on 2021-02-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilites', '0007_notification_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_name',
            field=models.CharField(max_length=300, null=True, verbose_name="Nom de l'utilisateur"),
        ),
    ]
