# Generated by Django 3.1.5 on 2021-05-21 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0015_auto_20210521_0905'),
        ('disponibilites', '0008_auto_20210218_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdv.responsable'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='evt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disponibilites.evenement'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='rdv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rdv.rendezvous'),
        ),
    ]
