# Generated by Django 3.1.5 on 2021-06-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilites', '0009_auto_20210521_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date_n',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='evt',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='heure_n',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='objet_n',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='rdv',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type_n',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_n',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='vue',
        ),
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.TextField(max_length=2000, null=True, verbose_name='Contenu du mail'),
        ),
        migrations.AddField(
            model_name='notification',
            name='cas',
            field=models.CharField(max_length=50, null=True, verbose_name='Cas de notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sujet',
            field=models.CharField(max_length=500, null=True, verbose_name='Subject'),
        ),
    ]
