# Generated by Django 3.1.5 on 2021-02-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauHoraire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField(null=True, verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(null=True, verbose_name='Heure de Fin')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='debut_pause',
            field=models.TimeField(null=True, verbose_name='Début de la pause'),
        ),
        migrations.AddField(
            model_name='service',
            name='duree_rdv',
            field=models.IntegerField(default=45, verbose_name='Durée des RDV dans ce service'),
        ),
        migrations.AddField(
            model_name='service',
            name='fin_pause',
            field=models.TimeField(null=True, verbose_name='Fin de la pause'),
        ),
        migrations.AddField(
            model_name='service',
            name='jour_ouverture_debut',
            field=models.CharField(default='Lundi', max_length=20, verbose_name="Jour d'ouverture debut"),
        ),
        migrations.AddField(
            model_name='service',
            name='jour_ouverture_fin',
            field=models.CharField(default='Vendredi', max_length=20, verbose_name="Jour d'ouverture fin"),
        ),
        migrations.AddField(
            model_name='service',
            name='creneaux',
            field=models.ManyToManyField(related_name='Creneaux_horaire_service', to='rdv.CreneauHoraire'),
        ),
    ]
