# Generated by Django 3.1.5 on 2021-02-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0002_auto_20210218_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='creneaux',
        ),
        migrations.RemoveField(
            model_name='service',
            name='jour_ouverture_debut',
        ),
        migrations.RemoveField(
            model_name='service',
            name='jour_ouverture_fin',
        ),
        migrations.AddField(
            model_name='creneauhoraire',
            name='jour',
            field=models.CharField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi')], default='Lundi', max_length=10, verbose_name='Jour de la semaine'),
        ),
        migrations.AddField(
            model_name='creneauhoraire',
            name='service',
            field=models.ManyToManyField(related_name='Service_du_crenneau', to='rdv.Service'),
        ),
    ]
