# Generated by Django 3.1.5 on 2021-02-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0003_auto_20210218_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneauhoraire',
            name='jour',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi')], default='Lundi', max_length=10, verbose_name='Jour de la semaine'),
        ),
    ]
