# Generated by Django 3.1.5 on 2021-02-19 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0004_auto_20210218_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneauhoraire',
            name='service',
        ),
        migrations.AddField(
            model_name='creneauhoraire',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rdv.service'),
        ),
    ]
