# Generated by Django 3.1.5 on 2021-02-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0006_client_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(default='password', max_length=300, verbose_name='Mot de passe'),
        ),
    ]
