# Generated by Django 3.1.5 on 2021-03-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0007_auto_20210224_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='responsable',
            field=models.ManyToManyField(related_name='Responsable_de_sevice', to='rdv.Responsable'),
        ),
    ]
