# Generated by Django 3.1.5 on 2021-03-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0009_remove_service_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='adresse',
            field=models.CharField(max_length=300, null=True, verbose_name='Adresse'),
        ),
    ]
