# Generated by Django 3.1.5 on 2021-03-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0010_auto_20210303_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(max_length=300, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=200, null=True, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.IntegerField(null=True, verbose_name='Téléphone'),
        ),
    ]
