# Generated by Django 3.1.5 on 2021-05-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0015_auto_20210521_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='couleur_conge',
            field=models.CharField(max_length=60, null=True, verbose_name='code couleur Jours off'),
        ),
        migrations.AddField(
            model_name='responsable',
            name='couleur_js',
            field=models.CharField(max_length=60, null=True, verbose_name='code couleur Jours spécifiques'),
        ),
    ]
