# Generated by Django 3.1.5 on 2021-06-02 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0016_auto_20210527_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rdv.responsable'),
        ),
    ]
