# Generated by Django 2.2.12 on 2021-10-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0017_rendezvous_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='login_zimbra',
            field=models.CharField(default='', max_length=100, null=True, verbose_name="Nom d'utilisateur zimbra"),
        ),
        migrations.AddField(
            model_name='responsable',
            name='mot_de_passe_zimbra',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Mot de passe Zimbra'),
        ),
    ]
