# Generated by Django 2.2.12 on 2021-11-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0018_auto_20211018_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='adresseTarvaux',
            field=models.CharField(default=' ', max_length=30, null=True, verbose_name='Adresse des travaux'),
        ),
    ]
